language: crystal
os:
- linux
dist: xenial

before_install:
  - sudo apt-get install -y libzstd-dev

script:
  - crystal spec
  - crystal tool format --check
  - shards build
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
