language: crystal
os:
- linux
dist: xenial

cache:
  directories:
    - "$HOME/zstd"

script:
  - crystal spec
  - crystal tool format --check
  - shards build
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
